name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-11.0
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run espresso tests
        uses: futureware-tech/simulator-action@v3
        with:
          api-level: 29
          script: ./gradlew connectedCheck

#      - run: mkdir -p app/build/reports/androidTests/connected

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected

  Compile:
    runs-on: ubuntu-latest
    needs: Unit-Test

    steps:
      - uses: actions/checkout@v2
        name: Checkout project

      - uses: actions/setup-java@v2
        name: Set up JDK
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - uses: actions/cache@v2
        name: Caching Gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release Bundle
        run: ./gradlew bundle

      - uses: r0adkll/sign-android-release@v1
        name: Sign Bundle
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: release.aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
